package kz.app.deliveryapp.support.stat;

public class Zvars {
    public static final String INDIGO_PRIVATE_PREFERENCES = "INDIGO_PRIVATE_PREFERENCES";
    static final String PREFERENCE_SECURE_AUTH_TOKEN_V_1 = "PREFERENCE_SECURE_AUTH_TOKEN_V_1";
    static final String PREFERENCE_DEBUG_HOST = "PREFERENCE_DEBUG_HOST";
    static final String PREFERENCE_SECURE_AUTH_TOKEN_TTL_V_1 = "PREFERENCE_SECURE_AUTH_TOKEN_TTL_V_1";
    static final String PREFERENCE_SECURE_REFRESH_TOKEN_V_1 = "PREFERENCE_SECURE_REFRESH_TOKEN_V_1";
    static final String PREFERENCE_USER_DATA = "PREFERENCE_USER_DATA";
    public static final String EXTRA_CICERONE_FRAGMENT = "EXTRA_CICERONE_FRAGMENT";
    public static final String ERROR_DATA_IS_NULL = "ERROR_DATA_IS_NULL";
    public static final String ERROR_REQUEST_RESULT_IS_NOT_SUCCESSFUL = "ERROR_REQUEST_RESULT_IS_NOT_SUCCESSFUL";
    public static final String EXTRA_PAGE = "EXTRA_PAGE";
    public static final String TOOLBAR_ICON_ARROW = "TOOLBAR_ICON_ARROW";
    public static final String TOOLBAR_ICON_HAMBURGER = "TOOLBAR_ICON_HAMBURGER";


    static final String PREFERENCE_LIST_PHOTO_CHILD = "PREFERENCE_LIST_PHOTO_CHILD";
}
